apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" . }}-gcp-scaler-editor-role
  labels:
  {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - gcp.k8scloudscaler
  resources:
  - scalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.k8scloudscaler
  resources:
  - scalers/status
  verbs:
  - get