apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" . }}-scaler-viewer-role
  labels:
  {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8s.cloudscaler.io
  resources:
  - scalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.cloudscaler.io
  resources:
  - scalers/status
  verbs:
  - get