# permissions for end users to view scalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudscaler
    app.kubernetes.io/managed-by: kustomize
  name: gcp-scaler-viewer-role
rules:
  - apiGroups:
      - gcp.cloudscaler.io
    resources:
      - scalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - gcp.cloudscaler.io
    resources:
      - scalers/status
    verbs:
      - get
