apiVersion: k8s.cloudscaler.io/v1alpha1
kind: Scaler
metadata:
  labels:
    app.kubernetes.io/name: cloudscaler
    app.kubernetes.io/managed-by: kustomize
  name: scaler-sample
spec:
  disableEvents: false
  resources:
    - deployments
    # - hpa
  namespaces:
    - home
  periods:
    - time:
        recurring:
          days:
            - all
          startTime: "01:00"
          endTime: "23:57"
          timezone: "Europe/Paris"
          once: false
          reverse: false
      minReplicas: 0
      maxReplicas: 10
      type: "down"
  labelSelector:
    matchLabels:
      app.kubernetes.io/name: backuppc
