processor:
  ignoreGroupVersions:
    - "GVK"
  ignoreTypes:
    - "Embedded[2-4]$"
  ignoreFields:
    - "status$"
    - "TypeMeta$"
  customMarkers:
    - name: "hidefromdoc"
      target: field

render:
  kubernetesVersion: 1.31
